# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_db
    volumes:
      - ./mysql_data:/data/db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db